server:
  port: 8089
spring:
  profiles:
    active: 218
  freemarker:
    cache: false
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/webapp/
rate-limit:
  stats:
    optimized: true

